### PR TITLE
Fix babel error This experimental syntax requires enabling the parser plugin: 'functionSent'

### PR DESCRIPTION
**Pull request by caub**

### CODE REVIEW

**Comment by brigand** [comment]
Example command that didn't work before but does work now, so I can verify this works?

**Comment by caub** [comment]
```
b> function* g(x){while(true); {console.log(x, function.sent); yield 1; return 1}} const f=g(3); f.next(4); f.next(5);
```

**Comment by brigand** [comment]
Without the semi after the `while(true)` it does seem to work after this change. Thanks.

```
me: b> function* g(x){while(true) {console.log(x, function.sent); yield 1; return 1}} const f=g(3); f.next(4); f.next(5);
bot: (okay) 3 4 { value: 1, done: true }
```

**Comment by caub** [comment]
Oh yea, right, that explains why my browser froze earlier, thanks

**Pull request merged**
