### PR TITLE
Upgrade a few babel proposals, fix record-and-tuple, add async-do-expressions, add a way to run js-eval tests without docker

### PR DESCRIPTION
**Pull request by caub**
Before upgrade, when testing locally I had a

```
> await babel.transformFromAstAsync(ast, code, {plugins: transformPlugins}).then((r) => r.code)
Uncaught TypeError: unknown: path.isStaticBlock is not a function
    at PluginPass.Class (/home/caub/dev/jellobot/node_modules/@babel/plugin-proposal-class-static-block/lib/index.js:48:27)
    at newFn (/home/caub/dev/jellobot/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/home/caub/dev/jellobot/node_modules/@babel/traverse/lib/path/context.js:55:20)
   ....
```
for some reason the error was not shown by bot, need to check this as well

### CODE REVIEW

**Comment by caub** [comment]
well still not working, will try again

**Comment by caub** [comment]
@ljharb ready for merge

only thing I couldn't find is a relevant decorators example/test case, the babel plugin seems not working well

I added a way to run tests and js-eval without docker

**Comment by ljharb** [comment]
@caub there's already commits on https://github.com/ljharb/jellobot that this isn't on top of; could we close this and you open a new one over there?

**Comment by caub** [comment]
Sure! https://github.com/ljharb/jellobot/pull/2

**Pull request closed without merging**
