### PR TITLE
add global.delay shortcut for promisified setTimeout

### PR DESCRIPTION
**Pull request by caub**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
Neither node nor the language has this, so this should not be added.

In node 15, you can `require(‘timers/promises‘).setTimeout` for this. Just use that.

**Comment by brigand** [comment]
I agree with ljharb here. It will cause confusion when we make up globals, since people will think they're available to their code.

A safer option would be to add real npm packages to node_modules (install with scripts disabled and fixed versions) and we might add a command or factoid that lists the installed packages.

**Comment by caub** [comment]
Ok guys, I removed the line about delay, and kept the function refactoring in case you think it's better

but I still think a bot should allow some shortcuts, because we have limited space for entering commands, etc..

using npm packages is still verbose due to require():

```
n> console.time(1); await require('delay')(200); console.timeEnd(1)
```

**Comment by ljharb** [comment]
in general, verbosity is preferred when it adds clarity.

**Comment by brigand** [comment]
I think the code is good either way, but the indirection with 'fn' is a bit odd, since we don't seem to use it with anything except require. Maybe something more like this?

```diff
- function defineGlobal(name, fn) {
+ function exposeBuiltinModule(name) {

-   const value = fn(name);
+   const value = require(name);
```

**Comment by brigand** [comment]
Oh, this protects against the user re-assigning global.require, right?

So it would make sense to alias require inside defineGlobal/exposeBuiltinModule.

**Comment by caub** [comment]
I don't remember exactly what it does, devsnek who wrote it said it's what node repl uses

It allows to overwrite those global builtins

**Comment by brigand** [comment]
Added a small fix and merged. Thanks.

**Pull request merged**
